### PR TITLE
Update to latest Gatsby beta

### PR DESCRIPTION
**Pull request by KyleAMathews**
It's not 100% working but you can get things running. Not entirely sure what broke but this should get you 75% of the way to upgrading to latest alpha. It's late here now but I'll start working on switching to gatsby-source-contentful tomorrow.

There's a lot of files changed. Most are from removing the `.cache` folder. This shouldn't be checked into Git as the data is derivative so no value in tracking it. Plus it changes often and would make for horrible diffs.

The other big changes are from my editor is setup to run [Prettier](https://github.com/prettier/prettier) on code when I save. Prettier is an awesome tool for ensuring code formatting is consistent across the team. I'd suggest we add an "format" script in the package.json.

Happy to answer questions about the PR once I wake and looking forward to chatting Friday!

### CODE REVIEW

**Comment by spatrame** [comment]
We have checking the solution and verifying. 
Could you please let us know once updated the code to beta version. 

I tried using gatsby-source-contentful plugin but getting some circularjson issue. I have raised and issue below
[https://github.com/gatsbyjs/gatsby/issues/1186](url)

**Comment by KyleAMathews** [comment]
I spent a while researching why the contentful source plugin was having trouble with this site and solved the circular JSON issue as well as another issue where apparently some entries/assets had been deleted in Contentful but were still referenced from other entries. The source plugin now automatically handles that.

I also set things up in the plugin + on this site so that markdown is rendered to HTML during build so we don't have to load markdown-in into the client to render things.

The PR is here: https://github.com/gatsbyjs/gatsby/pull/1202

I'll merge it tomorrow. I wanted to give the open source contributor who's done most of the work on the plugin time to review my changes before merging. Until then this PR won't work.

I also went ahead and added a "format" script to NPM to format/standardize code using Prettier. Lemme know how you like that.

**Comment by KyleAMathews** [comment]
I also restored the article-detail pages using the data from source-contentful.

See https://github.com/MindtreePGSSG/ModernWeb/blob/a0402b851ddf0e441e8066f1d0a5c82b9a9cd66c/gatsby-node.js where I create the pages and the updated page component https://github.com/MindtreePGSSG/ModernWeb/blob/a0402b851ddf0e441e8066f1d0a5c82b9a9cd66c/src/templates/articles/article-detail.js

I didn't dig in enough to figure out how you were constructing the URLs so that'll need updated.

This should give you a good taste on how to go about creating more pages.

Create the page in gatsby-node.js and pass the slug in as context and then use that to query for the data you need in the page component.

**Comment by KyleAMathews** [comment]
PR got reviewed so merged that and made a canary Gatsby release. Note: there is a weird GraphQL error (something to do with contentful source plugin) that I haven't found the source yet. It doesn't seem to affect the site however so ignore it until I find its source.

**Comment by spatrame** [comment]
I tried to excecute gatsby develop but showing below error,

initial sourcing and transforming nodes: 4333.070ms
UNHANDLED REJECTION Invariant Violation: Encountered an error trying to infer a GraphQL type for: "smartPhoneImage___NODE". There is no
corresponding node with the id field matching: "2eX2Bi0WSMq4uScYCo6uMS"

**Comment by spatrame** [comment]
**Note**: We have enabled localization in contentful for home page.  Hope Contentful source plugin is handling localization of content.

**Comment by KyleAMathews** [comment]
It turned out that the contentful source plugin had only been downloading 100 items and I guess y'all added a bunch of assets which caused the plugin to break. I fixed that and several other problems I discovered and made another release.

I also modified the develop (and added a build) npm scripts to run "yarn install" at the start. This is my favorite way to ensure a team of developers stays in sync.

**Comment by KyleAMathews** [comment]
>We have enabled localization in contentful for home page. Hope Contentful source plugin is handling localization of content.

I haven't investigated what the API does for localized source yet. Let's discuss tomorrow + I can look into this more.

**Comment by KyleAMathews** [comment]
Let's get this in before we diverge any further though :-)

**Comment by spatrame** [comment]
Can we have multiple URL's to the same html page.
Below is the one of the URL -
http://sample.domain.com/article/summer-article
And, I wants to have a tiny url as well which should refer to the same html page.
http://sample.domain.com/new-article

Is there any way to add route path without creating multiple HTML page. Can I refer two urls to the same page in gatsby?

Issue raised earlier:  https://github.com/gatsbyjs/gatsby/issues/1076

**Comment by KyleAMathews** [comment]
Didn't get the locale updates done today. Spent a bunch more time looking into it and thinking through alternatives and am pretty confident in my approach. Will implement in the morning.

**Comment by KyleAMathews** [comment]
Didn't end up getting to the locale fixes today. Made another beta release for Gatsby then got interested in integrating with Contentful's Image API 

https://www.contentful.com/developers/docs/references/images-api/

I added support for this to the contentful source plugin in https://github.com/gatsbyjs/gatsby/pull/1228

WIth this, it's very easy now to creative responsive images from assets you upload to Contentful. You can use either `responsiveResolution` or `responsiveSizes`. The first generates a srcSet with 1x, 1.5x, 2x, and 3x resolution images. The second generates a srcSet at the maxWidth then 1/4, 1/2, 1.5x, 2x, and 3x the widths. This is intended for images that are shown full-width on both larger and smaller screens.

I converted a bit of code over in
https://github.com/MindtreePGSSG/ModernWeb/pull/1/commits/d5060302a9217bc273334df487c4ef821f1100f2

**Comment by KyleAMathews** [comment]
With this you can just upload the full-sized original image and then query for what you need based on the design.

**Comment by spatrame** [comment]
I have updated gatsby, gatsby-source-contentful, gatsby-transformer-remark to canary version. when I run gatsby develop shows below error. let me know if any other plugin need to be installed. 

assets fetched 124
fetch Contentful data: 2614.602ms
initial sourcing and transforming nodes: 4698.628ms
UNHANDLED REJECTION Error: contentful__Asset.responsiveResolution field type must be Output Type but got: ContentfulResponsive Resolution.

**Comment by KyleAMathews** [comment]
Ugh no. That error happens when for some reason you have multiple versions
of graphql installed. I'm guessing versions across packages got out of
sync.

**Comment by spatrame** [comment]
Can i uninstall graphql and install again, will it work? 
Let me know if any other way to resolve.

**Comment by spatrame** [comment]
Which version of graphql will resolve this issue?

**Comment by KyleAMathews** [comment]
Just run "find . -name graphql" from the root of your site and then delete
extra copies.

I'm looking into the problem and will make a new release to fix it.

**Comment by KyleAMathews** [comment]
So the problem turned out to be that one of our dependencies from Facebook (relay-compiler) is on an old version of GraphQL so when I updated Gatsby's version of GraphQL, things broke. I downgraded Gatsby for now and updated the yarn.lock so we're fine again.

**Comment by KyleAMathews** [comment]
Starting in now on the locale updates.

**Comment by KyleAMathews** [comment]
Hmmm should stop promising locale support until it's done ;-)

Started on that but then realized that the Image API integration had some bugs then realized that the contentful source plugin needed a refactor to support adding localization support so did those plus made a bunch of tweaks to the website.

BTW, something to discuss tomorrow — thoughts on getting rid of SwiftType? It doesn't seem to be adding much and is slower than just creating our own browsing/searching/filtering experience. Probably not necessary to switch it out for this prototype but for the production version it'd be much nicer.

**Comment by KyleAMathews** [comment]
Oh and added a demo/documentation page on using the Gatsby/Contentful Image API integration https://using-contentful.gatsbyjs.org/image-api/

**Comment by KyleAMathews** [comment]
Making progress! https://59533279cf321c3a73a1a09d--using-contentful.netlify.com/products/c5KsDBWseXY6QegucYAoacS___de/

https://github.com/gatsbyjs/gatsby/pull/1279

**Comment by spatrame** [comment]
every time I run the code it occupied huge space in c drive.  Could you please let me know is it because of contentful-graphql plugin? how do I clear old version of data?

**Pull request merged**
